apiVersion: v1
kind: Service
metadata:
  labels:
    fdk.service: catalog-comments-service
  name: catalog-comments-service
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    fdk.service: catalog-comments-service
