name: Deploy to demo

on:
  repository_dispatch:
    types: [deploy-demo]

jobs:
  deploy-demo:
    name: Deploy latest production image to demo environment on repository dispatch
    uses: Informasjonsforvaltning/workflows/.github/workflows/deploy.yaml@test/hos/staging-maven-deploy
    with:
      app_name: catalog-comments-service
      caller_sha: ${{ github.event.client_payload.sha }}
      repo: ${{ github.repository }}
      actor: ${{ github.actor }}
      environment: 'demo'
      cluster: 'digdir-fdk-dev'
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
